# This package is a shared test suite and should only be used in test contexts.
name: kiss_queue_tests
description: A test suite for kiss_queue
version: 0.0.5
repository: https://github.com/WAMF/kiss_queue_tests

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.18.0
  test: ^1.24.0
  kiss_queue: ^0.1.2
  very_good_analysis: ^9.0.0

topics:
  - testing
